export enum ShopPattern {
  CREATE_SHOP = 'create_shop',
  EDIT_SHOP = 'edit_shop',
  ADD_PRODUCT = 'add_product',
  UPDATE_PRODUCT = 'update_product',
  DELETE_PRODUCT = 'delete_product',
  ADD_PRODUCT_DETAIL = 'add_product_detail',
  UPDATE_PRODUCT_DETAIL = 'update_product_detail',
  DELETE_PRODUCT_DETAIL = 'delete_product_detail',
  ADD_PRODUCT_COLOR = 'add_product_color',
  UPDATE_PRODUCT_COLOR = 'update_product_color',
  DELETE_PRODUCT_COLOR = 'delete_product_color',
  ALL_PRODUCT = 'all_product',
  CREATE_PRODUCT_SIZE = 'create_product_size',
  UPDATE_PRODUCT_SIZE = 'update_product_size',
  DELETE_PRODUCT_SIZE = 'delete_product_size',
}
